name: Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write
  packages: read

jobs:
  deploy:
    uses: LetStartCCorp/.github/.github/workflows/central-deploy.yml@main
    with:
      service_name: 'letstart-project-template'
    secrets: inherit
