name: Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    uses: LetStartCCorp/.github/.github/workflows/central-deploy.yml@main
    with:
      service_name: 'e-test-pack'
    secrets: inherit
